[project]
name = "odoo-addons-ecosoft-odoo-budgeting"
version = "18.0.20250618.0"
dependencies = [
    "odoo-addon-account_payment_multi_deduction_activity==18.0.*",
    "odoo-addon-base_tier_validation_check_budget==18.0.*",
    "odoo-addon-budget_activity==18.0.*",
    "odoo-addon-budget_activity_advance_clearing==18.0.*",
    "odoo-addon-budget_activity_expense==18.0.*",
    "odoo-addon-budget_activity_purchase==18.0.*",
    "odoo-addon-budget_activity_purchase_request==18.0.*",
    "odoo-addon-budget_control==18.0.*",
    "odoo-addon-budget_control_advance_clearing==18.0.*",
    "odoo-addon-budget_control_expense==18.0.*",
    "odoo-addon-budget_control_operating_unit==18.0.*",
    "odoo-addon-budget_control_purchase==18.0.*",
    "odoo-addon-budget_control_purchase_request==18.0.*",
    "odoo-addon-budget_control_request_document==18.0.*",
    "odoo-addon-budget_control_request_document_expense==18.0.*",
    "odoo-addon-budget_control_revision==18.0.*",
    "odoo-addon-budget_plan_detail==18.0.*",
    "odoo-addon-budget_plan_detail_advance_clearing==18.0.*",
    "odoo-addon-budget_plan_detail_expense==18.0.*",
    "odoo-addon-budget_plan_detail_purchase==18.0.*",
    "odoo-addon-budget_plan_detail_purchase_request==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
