import setuptools

with open('VERSION.txt', 'r') as f:
    version = f.read().strip()

setuptools.setup(
    name="odoo-addons-ecosoft-odoo-budgeting",
    description="Meta package for ecosoft-odoo-budgeting Odoo addons",
    version=version,
    install_requires=[
        'odoo-addon-account_asset_fund>=15.0dev,<15.1dev',
        'odoo-addon-account_asset_transfer_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-account_invoice_payment_retention_budget_control>=15.0dev,<15.1dev',
        'odoo-addon-account_payment_multi_deduction_activity>=15.0dev,<15.1dev',
        'odoo-addon-account_payment_multi_deduction_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-base_tier_validation_check_budget>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_advance_clearing>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_contract>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_contract_invoice_plan>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_expense>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_purchase>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_purchase_deposit>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_purchase_request>=15.0dev,<15.1dev',
        'odoo-addon-budget_activity_purchase_requisition>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_advance_clearing>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_contract>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_contract_invoice_plan>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_department>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_expense>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_operating_unit>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_operating_unit_access_all>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_purchase>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_purchase_deposit>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_purchase_request>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_purchase_requisition>=15.0dev,<15.1dev',
        'odoo-addon-budget_allocation_revision>=15.0dev,<15.1dev',
        'odoo-addon-budget_control>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_account_asset_management>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_advance_clearing>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_contract>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_exception>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_expense>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_operating_unit>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_operating_unit_access_all>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_purchase>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_purchase_manual_currency>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_purchase_request>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_purchase_requisition>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_purchase_work_acceptance_late_fines>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_queue>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_request_document>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_request_document_expense>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_revision>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_revision_lock_amount>=15.0dev,<15.1dev',
        'odoo-addon-budget_control_tier_validation>=15.0dev,<15.1dev',
        'odoo-addon-budget_plan>=15.0dev,<15.1dev',
        'odoo-addon-budget_plan_revision>=15.0dev,<15.1dev',
        'odoo-addon-budget_res_project_department>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_account_tax_expense_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_account_asset_management_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_hr_expense_activity>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_hr_expense_budget_control>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_purchase_agreement_budget_control>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_purchase_guarantee_activity>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_purchase_guarantee_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-l10n_th_gov_purchase_guarantee_operating_unit>=15.0dev,<15.1dev',
        'odoo-addon-purchase_stock_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-res_project>=15.0dev,<15.1dev',
        'odoo-addon-res_project_sequence>=15.0dev,<15.1dev',
        'odoo-addon-stock_budget_allocation>=15.0dev,<15.1dev',
        'odoo-addon-stock_request_budget_allocation>=15.0dev,<15.1dev',
    ],
    classifiers=[
        'Programming Language :: Python',
        'Framework :: Odoo',
        'Framework :: Odoo :: 15.0',
    ]
)
